/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "Wo5dMEP_BbI",
    title: "Kevin Hart - I'm Scared Of Ostriches",
    description:
      "Comedy superstart #KevinHart (Think Like A Man, Ride Along, Top Five) graced the Montreal stage at the Just for Laughs ...",
    creator: "Kevin Hart",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/WmIS_icNcLk/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBKf25HoKWqAD4Wx6GuqOWMOWTuDA",
    year: 7,
    views: "8.2M",
    genre: "Anecdotal Comedy",
    nationality: "US",
    popularity: "International",
  },
  {
    _id: "Adffdgssj_BbK",
    title: "Rowan Atkinson - Going On Your First Date",
    description:
      "RowanAtkinson, actor and comedian best known for his work as #MrBean , hilariously acts out what a #firstdate is really like.",
    creator: "Rowan Atkinson",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/mm1HgQbXFEE/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCA804r1Yv3ItqhsZsEBzUmemDadA",
    year: 6,
    views: "7.4M",
    genre: "Improv",
    nationality: "US",
    popularity: "International",
  },
  {
    _id: "Y_RddhshYRJ",
    title: "Dave Chappelle - Super Heroes Are Bad Role Models",
    creator: "Sentdex",
    description:
      "DaveChappelle (Chappelle's Show, Half Baked… you know who he is!) on #Montreal 's black community, racial tension, and his ...",
    creator: "Dave Chappelle",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/zNyqYOUxBrY/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBnAOZKEEmxm0NUkHjwCgDhUqWl4A",
    year: 6,
    views: "7M",
    genre: "Satire",
    nationality: "US",
    popularity: "International",
  },
  {
    _id: "HdshsHDSSR",
    title: "Hasan Minhaj - White People At Indian Weddings",
    description:
      "HasanMinhaj on getting engaged, how white people act at Indian weddings, and how much immigrants love secrets.",
    creator: "Hasan Minhaj",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/nNx5tnqD9e0/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAtr89SQWhxvqQ-E_4q-ZEdgux21A",
    year: 3,
    views: "4.5M",
    genre: "Anecdotal Comedy",
    nationality: "US",
    popularity: "International",
  },
  {
    _id: "SGGhajjfxH",
    title: "Chris Rock - Women Don't Like Nice Guys",
    description:
      "Legendary stand-up comedian #ChrisRock (Saturday Night Live, Everybody Hates Chris, Top Five) has graced the Montreal ...",
    creator: "Chris Rock",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/28vas-3WmUg/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA6ejtL-Y_-ROm7vlOwPxFg3nKZEA",
    year: 8,
    views: "2M",
    genre: "Dark Comedy",
    nationality: "US",
    popularity: "International",
  },
  {
    _id: "KhdhdsFAHJ",
    title: "Vir Das - Women Are Like Canada",
    description:
      "VirDas on different cultural stereotypes, how humanity has ruined religion, and his elaborate plan to end sexism. #VirDasStandUp ...",
    creator: "Vir Das",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/T0lGP0FeZ7Y/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDXaRSRlwDuBI1DEV-Lo81ejropSQ",
    year: 2,
    views: "2.7M",
    genre: "Observational Comedy",
    nationality: "Indian",
    popularity: "International",
  },
  {
    _id: "OPswgwgzgzY",
    title: "Ali Wong - Why I Want To Get Married",
    description:
      "AliWong on how marriage will make her life easier, choosing between the Tonight Show and her boyfriend, and how she could ...",
    creator: "Ali Wong",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/oItPQRZ3xpI/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLARRx_vKhF-mk8v5L8XGHF5GlBX_A",
    year: 4,
    views: "3M",
    genre: "Observational Comedy",
    nationality: "US",
    popularity: "International",
  },
  {
    _id: "MswsffsTYE",
    title: "John Mulaney - Back To The Future Is Very Weird",
    description:
      "JohnMulaney on getting his email hacked, turning 30, and how thin the plot to Back To The Future was. #JohnMulaneyStand Up ...",
    creator: "John Mulaney",
    channelName: "Just for Laughs",
    img: "https://i.ytimg.com/vi/ButlizwQXnU/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC8na2iVJUeVlnGIfzw5OwbNJvbtQ",
    year: 5,
    views: "4.9M",
    genre: "Anecdotal Comedy",
    nationality: "US",
    popularity: "International",
  },
];
